//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:25:27 下午 CST 
//


package cn.summer.bus_side.domainCES011;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BusiType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="BusiType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="BT01"/>
 *     &lt;enumeration value="BT02"/>
 *     &lt;enumeration value="BT03"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "BusiType")
@XmlEnum
public enum BusiType {

    @XmlEnumValue("BT01")
    BT_01("BT01"),
    @XmlEnumValue("BT02")
    BT_02("BT02"),
    @XmlEnumValue("BT03")
    BT_03("BT03");
    private final String value;

    BusiType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static BusiType fromValue(String v) {
        for (BusiType c: BusiType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
