//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:25:27 下午 CST 
//


package cn.summer.bus_side.domainCES011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Document complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Document">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MainBody" type="{}MainBody"/>
 *         &lt;element name="PtcptSgntr" type="{}PtcptSgntr"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Document", propOrder = {
    "mainBody",
    "ptcptSgntr"
})
public class Document {

    @XmlElement(name = "MainBody", required = true)
    protected MainBody mainBody;
    @XmlElement(name = "PtcptSgntr", required = true)
    protected String ptcptSgntr;

    /**
     * Gets the value of the mainBody property.
     * 
     * @return
     *     possible object is
     *     {@link MainBody }
     *     
     */
    public MainBody getMainBody() {
        return mainBody;
    }

    /**
     * Sets the value of the mainBody property.
     * 
     * @param value
     *     allowed object is
     *     {@link MainBody }
     *     
     */
    public void setMainBody(MainBody value) {
        this.mainBody = value;
    }

    /**
     * Gets the value of the ptcptSgntr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPtcptSgntr() {
        return ptcptSgntr;
    }

    /**
     * Sets the value of the ptcptSgntr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPtcptSgntr(String value) {
        this.ptcptSgntr = value;
    }

}
