//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:25:27 下午 CST 
//


package cn.summer.bus_side.domainCES011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MainBody complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MainBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="MsgId" type="{}MsgId"/>
 *         &lt;element name="OrgnlMsgId" type="{}OrgnlMsgId"/>
 *         &lt;element name="QuoteInf" type="{}QuoteInf"/>
 *         &lt;element name="RecInf" type="{}RecInf"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MainBody", propOrder = {
    "msgId",
    "orgnlMsgId",
    "quoteInf",
    "recInf"
})
public class MainBody {

    @XmlElement(name = "MsgId", required = true)
    protected MsgId msgId;
    @XmlElement(name = "OrgnlMsgId", required = true)
    protected OrgnlMsgId orgnlMsgId;
    @XmlElement(name = "QuoteInf", required = true)
    protected QuoteInf quoteInf;
    @XmlElement(name = "RecInf", required = true)
    protected RecInf recInf;

    /**
     * Gets the value of the msgId property.
     * 
     * @return
     *     possible object is
     *     {@link MsgId }
     *     
     */
    public MsgId getMsgId() {
        return msgId;
    }

    /**
     * Sets the value of the msgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link MsgId }
     *     
     */
    public void setMsgId(MsgId value) {
        this.msgId = value;
    }

    /**
     * Gets the value of the orgnlMsgId property.
     * 
     * @return
     *     possible object is
     *     {@link OrgnlMsgId }
     *     
     */
    public OrgnlMsgId getOrgnlMsgId() {
        return orgnlMsgId;
    }

    /**
     * Sets the value of the orgnlMsgId property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrgnlMsgId }
     *     
     */
    public void setOrgnlMsgId(OrgnlMsgId value) {
        this.orgnlMsgId = value;
    }

    /**
     * Gets the value of the quoteInf property.
     * 
     * @return
     *     possible object is
     *     {@link QuoteInf }
     *     
     */
    public QuoteInf getQuoteInf() {
        return quoteInf;
    }

    /**
     * Sets the value of the quoteInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link QuoteInf }
     *     
     */
    public void setQuoteInf(QuoteInf value) {
        this.quoteInf = value;
    }

    /**
     * Gets the value of the recInf property.
     * 
     * @return
     *     possible object is
     *     {@link RecInf }
     *     
     */
    public RecInf getRecInf() {
        return recInf;
    }

    /**
     * Sets the value of the recInf property.
     * 
     * @param value
     *     allowed object is
     *     {@link RecInf }
     *     
     */
    public void setRecInf(RecInf value) {
        this.recInf = value;
    }

}
