//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:25:27 下午 CST 
//


package cn.summer.bus_side.domainCES011;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for RecInf complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="RecInf">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RecBranch" type="{}MaxMin9NumericText"/>
 *         &lt;element name="RecUser" type="{}Max10AlphaNumericText"/>
 *         &lt;element name="RecProductId" type="{}MaxMin9NumericText" minOccurs="0"/>
 *         &lt;element name="RecCmd" type="{}RecCmd"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "RecInf", propOrder = {
    "recBranch",
    "recUser",
    "recProductId",
    "recCmd"
})
public class RecInf {

    @XmlElement(name = "RecBranch", required = true)
    protected String recBranch;
    @XmlElement(name = "RecUser", required = true)
    protected String recUser;
    @XmlElement(name = "RecProductId")
    protected String recProductId;
    @XmlElement(name = "RecCmd", required = true)
    protected String recCmd;

    /**
     * Gets the value of the recBranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecBranch() {
        return recBranch;
    }

    /**
     * Sets the value of the recBranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecBranch(String value) {
        this.recBranch = value;
    }

    /**
     * Gets the value of the recUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecUser() {
        return recUser;
    }

    /**
     * Sets the value of the recUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecUser(String value) {
        this.recUser = value;
    }

    /**
     * Gets the value of the recProductId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecProductId() {
        return recProductId;
    }

    /**
     * Sets the value of the recProductId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecProductId(String value) {
        this.recProductId = value;
    }

    /**
     * Gets the value of the recCmd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRecCmd() {
        return recCmd;
    }

    /**
     * Sets the value of the recCmd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRecCmd(String value) {
        this.recCmd = value;
    }

}
