//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:25:27 下午 CST 
//


package cn.summer.bus_side.domainCES001;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the cn.river.practice.msg_class.CES001Msg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Document_QNAME = new QName("", "Document");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: cn.river.practice.msg_class.CES001Msg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link CpInf }
     * 
     */
    public CpInf createCpInf() {
        return new CpInf();
    }

    /**
     * Create an instance of {@link SlfInf }
     * 
     */
    public SlfInf createSlfInf() {
        return new SlfInf();
    }

    /**
     * Create an instance of {@link OrgnlMsgId }
     * 
     */
    public OrgnlMsgId createOrgnlMsgId() {
        return new OrgnlMsgId();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link Bill }
     * 
     */
    public Bill createBill() {
        return new Bill();
    }

    /**
     * Create an instance of {@link MainBody }
     * 
     */
    public MainBody createMainBody() {
        return new MainBody();
    }

    /**
     * Create an instance of {@link MsgId }
     * 
     */
    public MsgId createMsgId() {
        return new MsgId();
    }

    /**
     * Create an instance of {@link Blist }
     * 
     */
    public Blist createBlist() {
        return new Blist();
    }

    /**
     * Create an instance of {@link QuoteInf }
     * 
     */
    public QuoteInf createQuoteInf() {
        return new QuoteInf();
    }

    /**
     * Create an instance of {@link QuoteFctInf }
     * 
     */
    public QuoteFctInf createQuoteFctInf() {
        return new QuoteFctInf();
    }

    /**
     * Create an instance of {@link CurrencyAndAmount }
     * 
     */
    public CurrencyAndAmount createCurrencyAndAmount() {
        return new CurrencyAndAmount();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Document }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Document")
    public JAXBElement<Document> createDocument(Document value) {
        return new JAXBElement<Document>(_Document_QNAME, Document.class, null, value);
    }

}
