//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-833 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.30 at 10:25:27 下午 CST 
//


package cn.summer.bus_side.domainCES001;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SlfInf complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SlfInf">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ReqBranch" type="{}MaxMin9NumericText"/>
 *         &lt;element name="ProductId" type="{}MaxMin9NumericText" minOccurs="0"/>
 *         &lt;element name="ReqUser" type="{}Max10AlphaNumericText"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SlfInf", propOrder = {
    "reqBranch",
    "productId",
    "reqUser"
})
public class SlfInf {

    @XmlElement(name = "ReqBranch", required = true)
    protected String reqBranch;
    @XmlElement(name = "ProductId")
    protected String productId;
    @XmlElement(name = "ReqUser", required = true)
    protected String reqUser;

    /**
     * Gets the value of the reqBranch property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqBranch() {
        return reqBranch;
    }

    /**
     * Sets the value of the reqBranch property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqBranch(String value) {
        this.reqBranch = value;
    }

    /**
     * Gets the value of the productId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProductId() {
        return productId;
    }

    /**
     * Sets the value of the productId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProductId(String value) {
        this.productId = value;
    }

    /**
     * Gets the value of the reqUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReqUser() {
        return reqUser;
    }

    /**
     * Sets the value of the reqUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReqUser(String value) {
        this.reqUser = value;
    }

}
